#!/bin/bash
echo "nameserver 1.1.1.1" > /etc/resolv.conf
echo -e "------------------------------\n"
echo -e "Escolha uma radio para escutar:\n"
echo -e "1 - Radio Web Campos Borges (emissora principal)\n"
echo -e "2 - Assistir TV\n"
echo -e "3 - Configuracoes do sistema\n"
echo -e "------------------------------\n"
read opcao
if [[ "$opcao" == "1" ]];then
echo -e "Conectando a emissora Radio Web Campos Borges...\n"
mplayer -ao pulse -volume 100 -loop 0 -nocache http://rdcamposborgesrs.com:8081/rdcamposborgesweb
exec /usr/local/bin/shell_radio
fi
if [[ "$opcao" == "2" ]];then
echo -e "Conectando a emissora Radio Web Campos Borges...\n"
wget https://pastebin.com/raw/EWmtd7Xc -O /tmp/channels.m3u
mplayer -ao pulse -vo sdl -volume 100 -loop 0 -nocache -playlist /tmp/channels.m3u
exec /usr/local/bin/shell_radio
fi
if [[ "$opcao" == "3" ]];then
echo -e "---------------------------\n"
echo -e "Configuracoes do sistema\n"
echo -e "1 - Conectar Internet cabeada\n"
echo -e "2 - Conectar Wifi (Internet sem fio)\n"
echo -e "3 - Desconectar Wifi (Internet sem fio)\n"
echo -e "4 - Aumentar volume da radio\n"
echo -e "5 - Diminuir volume da radio\n"
echo -e "6 - Adicionar rede Wifi(Internet sem fio)\n"
echo -e "7 - Atualizar os arquivos necessarios para funcionar recepcao de radio e conexao a internet\n)"
echo -e "8 - Desligar o radio\n"
echo -e "9 - Reiniciar o radio\n"
echo -e "----------------------------\n"
read opcao
if [[ "$opcao" == "1" ]];then
dhclient eth0
exec /usr/local/bin/shell_radio
fi
if [[ "$opcao" == "2" ]];then
wpa_supplicant -D nl80211 -c /etc/wpa_supplicant.conf -i wlan0 &
sleep 2
dhclient wlan0
exec /usr/local/bin/shell_radio
fi
if [[ "$opcao" == "3" ]];then
killall wpa_supplicant
killall dhclient
exec /usr/local/bin/shell_radio
fi
if [[ "$opcao" == "4" ]];then
pactl set-sink-volume 0 +20%
exec /usr/local/bin/shell_radio
fi
if [[ "$opcao" == "5" ]];then
pactl set-sink-volume 0 -20%
exec /usr/local/bin/shell_radio
fi
if [[ "$opcao" == "6" ]];then
echo -e "Qual o SSID (nome da rede Wifi) que deseja conectar?\n"
read ssid
echo -e "Qual a senha da rede Wifi?\n"
read senha
wpa_passphrase $ssid $senha > /etc/wpa_supplicant.conf
exec /usr/local/bin/shell_radio
fi
if [[ "$opcao" == "7" ]];then
echo -e "Atualizando o radio...\n"
echo -e "POR FAVOR NAO DESLIGUE OU REINICIE O RADIO!!!\n"
echo -e "Ao final da atualizacao o radio sera reiniciado automaticamente!!!\n"
sudo -u root -g root wget https://raw.githubusercontent.com/Cristian0808/linux-radio-internet/main/shell_radio -O /usr/local/bin/shell_radio
sudo -u root -g root chmod 777 /usr/local/bin/shell_radio
echo -e "Reiniciando o radio...\n"
reboot
fi
if [[ "$opcao" == "8" ]];then
shutdown now
fi
if [[ "$opcao" == "9" ]];then
reboot
fi
if [[ "$opcao" == "" ]];then
exec /usr/local/bin/shell_radio
fi
fi
if [[ "$opcao" == "" ]];then
exec /usr/local/bin/shell_radio
fi
